Repository vito/bass, pull requests merged in 2022-04, with the labels that each got.

#117 fix up logging
  ci/shipit
  project.bass
Labels: chore

#118 binding a :keyword is const compare with Symbol instead
  pkg/bass/binding_test.go
  pkg/bass/keyword.go
Labels: enhancement, breaking

#119 cons forms satisfy `pair?`
  pkg/bass/ground.go
  pkg/bass/ground_test.go
Labels: enhancement, breaking

#121 bump buildkit to v0.10.0 final
  .gitignore
  go.mod
  go.sum
  nix/vendorSha256.txt
Labels: chore

#120 add (curryfn), use it for defining path roots
  demos/curry.bass
  pkg/bass/ground_test.go
  pkg/lsp/analyzer.go
  std/git.bass
  std/root.bass
Labels: enhancement

#122 pretty traces
  cmd/bass/main.go
  cmd/bass/progress.go
  cmd/bass/repl.go
  docs/go/bass.go
  docs/go/lexer.go
  docs/go/syntax.go
  go.mod
  go.sum
  nix/vendorSha256.txt
  pkg/bass/range.go
  pkg/bass/trace.go
  pkg/bass/trace_test.go
  pkg/cli/error.go
  pkg/cli/progress.go
  pkg/hl/lexer.go
  pkg/lsp/handler.go
  pkg/runtimes/suite.go
Labels: enhancement

#123 rebuild docs
  docs/bassics.html
  docs/guide.html
  docs/index.html
  docs/stdlib.html
Labels: chore

#125 nicer error formatting, detailed thunk errors
  .bassignore
  cmd/bass/progress.go
  demos/multi-fail.bass
  pkg/runtimes/buildkit.go
Labels: enhancement

#126 Update CONTRIBUTING.md
  CONTRIBUTING.md
Labels: chore

#129 v0.3.0 notes + rebuild docs
  docs/bassics.html
  docs/guide.html
  docs/index.html
  docs/stdlib.html
  notes/v0.3.0.md
Labels: chore

#130 bump tabs for newer gh
  bass.lock
Labels: chore

#132 fix lsp test logging location
  pkg/lsp/testdata/config.vim
Labels: chore

#133 bump op cli to v2, add with-creds script
  .gitignore
  hack/ship
  hack/with-creds
Labels: chore

#134 add (module)
  pkg/bass/ground_test.go
  pkg/bass/stdlib.go
  std/lists.bass
  std/root.bass
Labels: enhancement

#135 add (with-cmd), (thunk-args), Go->Bass (wrap-cmd)
  pkg/bass/ground.go
  pkg/bass/thunk.go
  std/run.bass
Labels: enhancement

#136 bump tabs for new gh api
  bass.lock
  ci/shipit
  project.bass
Labels: chore

#137 much faster oci archive image test
  pkg/runtimes/suite.go
  pkg/runtimes/testdata/oci-archive-hello.nix
  pkg/runtimes/testdata/oci-archive-image.bass
Labels: chore

#138 memos: use explicit `*memos*` binding instead of searching from caller's `*dir*`
  nix/images.bass
  pkg/bass/memo.go
  pkg/bass/memo_test.go
  project.bass
  project.lock
  std/git.bass
  std/run.bass
Labels: enhancement, breaking

#139 nicer unbound symbol err: suggest similar bindings
  demos/unbound-error.bass
  go.mod
  pkg/bass/errors.go
  pkg/bass/errors_test.go
  pkg/bass/eval_test.go
  pkg/bass/ground_test.go
  pkg/bass/scope.go
  pkg/bass/symbol.go
  pkg/bass/symbol_test.go
Labels: enhancement

#140 pretty backtraces for repl, nice reader errors
  cmd/bass/main.go
  pkg/bass/errors.go
  pkg/bass/range.go
  pkg/bass/reader.go
  pkg/cli/error.go
  pkg/cli/repl.go
Labels: enhancement

#141 v0.4.0 notes
  ci/shipit
  notes/v0.4.0.md
Labels: chore

#146 binding `{binds}`
  pkg/bass/bind.go
  pkg/bass/binding_test.go
  pkg/lsp/testdata/gd.bass
Labels: enhancement

#147 add `--input` (`-i`) flag for passing inputs on stdin
  cmd/bass/export.go
  cmd/bass/main.go
  cmd/bass/run.go
  docs/go/bass.go
  pkg/bass/fspath.go
  pkg/bass/host_path.go
  pkg/bass/json.go
  pkg/bass/json_test.go
  pkg/bass/memo.go
  pkg/bass/pipes.go
  pkg/bass/scope.go
  pkg/bass/secret.go
  pkg/bass/thunk.go
  pkg/bass/thunk_path.go
  pkg/bass/thunk_path_test.go
  pkg/bass/thunk_types.go
  pkg/bass/value.go
  pkg/bass/value_test.go
  pkg/cli/inputs.go
  pkg/cli/inputs_test.go
  pkg/runtimes/buildkit.go
Labels: enhancement

#148 add `(across)` and `(for)`, for consuming/looping over streams in parallel
  pkg/bass/across.go
  pkg/bass/across_test.go
  pkg/bass/ground.go
  pkg/bass/ground_test.go
  std/streams.bass
Labels: enhancement
